language: python
python:
- '3.5'
install:
- python setup.py install
script:
- python -m unittest discover -s tests
addons:
  apt_packages:
  - pandoc
before_deploy:
- pandoc --from=markdown --to=rst --output=README.rst README.md
deploy:
  provider: pypi
  user: childsish
  password:
    secure: Df80wcXWFkXJLcJLqllGu1xFbfPWYFFeVbNjjKg3tls6Xli5/2qEDgonjPOwly9lsXjvg1rJyaxIhE/6q6H0VdrebkfqpkDXQ7MQ9iHG9T+GoCCyUv7jH46UjDri6M9wCwpkbzpZCSrelfogULU+UJdJKHkQiP/8S/gHfxKh9LMUPqBvoF9z6C9ffEiF5a4xw1sx2ORFOpy82BMFkGz9TMkvEolsdfFxl1YHL2BXP03C1XJFSD29uXXJoeampUTgWd8PCAARQCd/pTjQV0qbVIjWK7VsbYzqyyh3s2LVZpOyXvhZhYzVzc07luHfnj4VcZZfZi6bWIovOMvGKsBxzSM0W1hhCtvmLYuowAeApfHch/6LZ7BGKQhnpegKRBuMty4EEwBUCi2EcMxx0mrmCWzj85XonbDUk2jAo0iS6I2o6z/leyb2T7Jpahcttez1nHwejfIEhWIelLg/nS+N3+oxU0Ksxdv5Kc7AxZocLDauSWFYi2QJHQGDcuLnmPEvuFKVBWF+lupV6rHfYWtd2dxk0dpC0UMs8vLkSFKOfpAZEb5rZxNa/MZD8EVHvnnYvCUu4t5LlmaA2tuq3txyisIFrfDB08Myr+6iyO0Vm5iNjmpH+W2ve8lx320aXY5WQ1XRpHO3YpstPrWDN18xcOAB97RGQV9gfJBPRXlpbq4=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: childsish/mimo
